import type { Bi } from "../types";
export const STRINGS = {
  "app.title": { en: "Tìm Con Heo", vi: "Tìm Con Heo" },
  "app.dialect": { en: "Đà Nẵng", vi: "Đà Nẵng" },
  "app.tagline": { en: "Read Vietnamese for real", vi: "Đọc tiếng Việt thật" },
  "app.loading": { en: "Loading your garden…", vi: "Đang mở khu vườn của bạn…" },
  "nav.home": { en: "Home", vi: "Hôm nay" }, "nav.library": { en: "Library", vi: "Thư viện" }, "nav.review": { en: "Review", vi: "Ôn tập" }, "nav.tones": { en: "Tones", vi: "Thanh điệu" }, "nav.words": { en: "Words", vi: "Từ của tôi" },
  "nav.garden": { en: "Garden", vi: "Vườn" }, "nav.import": { en: "My text", vi: "Bài riêng" }, "nav.about": { en: "About", vi: "Về ứng dụng" }, "nav.menu": { en: "Open menu", vi: "Mở trình đơn" }, "nav.close": { en: "Close", vi: "Đóng" }, "nav.back": { en: "Back", vi: "Về" }, "nav.signOut": { en: "Sign out", vi: "Đăng xuất" }, "nav.theme": { en: "Change theme", vi: "Đổi giao diện" }, "nav.language": { en: "Language", vi: "Ngôn ngữ" },
  "nav.voice": { en: "Voice", vi: "Voice" }, "nav.languageBilingual": { en: "English + Vietnamese", vi: "Anh + Việt" }, "nav.languageEnglish": { en: "English only", vi: "Chỉ tiếng Anh" }, "nav.languageVietnamese": { en: "Vietnamese first", vi: "Ưu tiên tiếng Việt" },
  "home.eyebrow": { en: "A small daily reading habit", vi: "Một thói quen đọc nhỏ mỗi ngày" }, "home.greeting": { en: "Hello, read one good line", vi: "Chào bạn, đọc một câu thật hay" }, "home.intro": { en: "No streaks or pressure. Just a little Vietnamese, with a patient ear for Đà Nẵng.", vi: "Không áp lực hay chuỗi ngày. Chỉ một chút tiếng Việt, với đôi tai kiên nhẫn cho giọng Đà Nẵng." }, "home.continue": { en: "Continue reading", vi: "Đọc tiếp" }, "home.start": { en: "Start reading", vi: "Bắt đầu đọc" }, "home.reread": { en: "Read again", vi: "Đọc lại" }, "home.ready": { en: "Ready for you", vi: "Đang chờ bạn" }, "home.sorted": { en: "Stories are ordered toward your next comfortable step.", vi: "Truyện được xếp theo bước tiếp theo vừa sức với bạn." },
  "home.known": { en: "rooted words", vi: "từ đã bén rễ" }, "home.syllables": { en: "syllables read", vi: "âm tiết đã đọc" }, "home.sessions": { en: "reading days", vi: "ngày đã đọc" }, "home.toneTitle": { en: "Hear the Central difference", vi: "Nghe khác biệt miền Trung" }, "home.toneBody": { en: "Hỏi and ngã merge in Đà Nẵng. Learn the contour without pretending the written marks disappear.", vi: "Hỏi và ngã hòa vào nhau ở Đà Nẵng. Học đường nét âm thanh mà không giả vờ dấu viết biến mất." }, "home.reviewTitle": { en: "A gentle review", vi: "Một lượt ôn nhẹ nhàng" }, "home.reviewBody": { en: "The clock makes the promise, not a card count.", vi: "Đồng hồ giữ lời hứa, không phải số thẻ." }, "home.importTitle": { en: "Have a Vietnamese text?", vi: "Có một đoạn tiếng Việt?" }, "home.importBody": { en: "Paste it here and make it readable.", vi: "Dán vào đây để biến thành bài đọc." },
  "library.title": { en: "Library", vi: "Thư viện" }, "library.intro": { en: "Everything is available. Difficulty sorts the path; it never locks a door.", vi: "Mọi bài đều mở. Độ khó chỉ xếp đường đi, không khóa cánh cửa nào." }, "library.sortReadiness": { en: "Best next", vi: "Vừa sức nhất" }, "library.sortDifficulty": { en: "Intrinsic difficulty", vi: "Độ khó nội tại" }, "library.filterAll": { en: "All", vi: "Tất cả" }, "library.why": { en: "Why this rating", vi: "Vì sao xếp hạng này" }, "library.read": { en: "Open story", vi: "Mở bài đọc" },
  "reader.full": { en: "Full help", vi: "Đầy đủ" }, "reader.assisted": { en: "Guided", vi: "Có gợi ý" }, "reader.raw": { en: "Plain text", vi: "Văn bản" }, "reader.listenAll": { en: "Listen to all", vi: "Nghe toàn bài" }, "reader.stop": { en: "Stop", vi: "Dừng" }, "reader.listenSentence": { en: "Listen to sentence", vi: "Nghe câu" }, "reader.complete": { en: "I finished reading", vi: "Tôi đã đọc xong" }, "reader.done": { en: "A small thing, read well.", vi: "Một điều nhỏ, đọc thật kỹ." }, "reader.source": { en: "Source", vi: "Nguồn" }, "reader.remember": { en: "Save for review", vi: "Lưu để ôn lại" }, "reader.wordStatus": { en: "How well do you know this word?", vi: "Bạn biết từ này đến đâu?" }, "reader.new": { en: "New", vi: "Mới" }, "reader.learning": { en: "Learning", vi: "Đang học" }, "reader.known": { en: "Known", vi: "Đã biết" }, "reader.ignored": { en: "Skip", vi: "Bỏ qua" },
  "review.title": { en: "Review for a while", vi: "Ôn tập một lúc" }, "review.intro": { en: "Choose a time box. The clock ends the session; nothing is lost if you stop.", vi: "Chọn một khoảng thời gian. Đồng hồ kết thúc lượt học; dừng lại cũng không mất gì." }, "review.minutes": { en: "minutes", vi: "phút" }, "review.start": { en: "Start gently", vi: "Bắt đầu nhẹ nhàng" }, "review.end": { en: "End session", vi: "Kết thúc lượt học" }, "review.left": { en: "about {minutes} minutes left", vi: "còn khoảng {minutes} phút" }, "review.almost": { en: "almost done", vi: "sắp xong" }, "review.reveal": { en: "Show meaning", vi: "Xem nghĩa" }, "review.again": { en: "Again", vi: "Lại lần nữa" }, "review.hard": { en: "Hard", vi: "Khó" }, "review.good": { en: "Good", vi: "Được rồi" }, "review.easy": { en: "Easy", vi: "Dễ" }, "review.emptyTitle": { en: "Nothing is due right now", vi: "Bây giờ chưa có từ nào đến hạn" }, "review.emptyBody": { en: "Save a word while reading and it will return here when it is ready.", vi: "Lưu một từ khi đọc, từ sẽ quay lại đây khi đến lúc." }, "review.context": { en: "A sentence from your reading", vi: "Một câu từ bài bạn đã đọc" }, "review.forgiveness": { en: "Welcome back — I spread your reviews over the next few weeks. Nothing was lost.", vi: "Mừng bạn quay lại — các lượt ôn đã được trải ra trong vài tuần tới. Không có gì bị mất." },
  "tones.title": { en: "Find the shape of a voice", vi: "Tìm đường nét của giọng" }, "tones.intro": { en: "Đà Nẵng keeps hỏi and ngã close. The written marks remain; your ear learns the living contour.", vi: "Đà Nẵng giữ hỏi và ngã gần nhau. Dấu viết vẫn còn; tai bạn học đường nét đang sống." }, "tones.listen": { en: "Listen", vi: "Nghe" }, "tones.record": { en: "Record", vi: "Ghi âm" }, "tones.stop": { en: "Stop", vi: "Dừng" }, "tones.choose": { en: "Choose the tone you heard", vi: "Chọn thanh bạn vừa nghe" }, "tones.demo": { en: "Demonstration: mả / mã merge in Đà Nẵng — there is no wrong answer here.", vi: "Minh họa: mả / mã hòa vào nhau ở Đà Nẵng — bài này không có đáp án sai." }, "tones.check": { en: "Play a real five-choice check", vi: "Làm bài kiểm tra năm lựa chọn" }, "tones.correct": { en: "Good ear.", vi: "Tai nghe tốt." }, "tones.tryAgain": { en: "Not quite. Listen to the contour again.", vi: "Chưa đúng. Hãy nghe lại đường nét." },
  "words.title": { en: "Your words", vi: "Từ của tôi" }, "words.intro": { en: "Known words and learning words are allowed to be different things.", vi: "Từ đã biết và từ đang học có thể là hai chuyện khác nhau." }, "words.search": { en: "Search a word", vi: "Tìm một từ" }, "words.all": { en: "All", vi: "Tất cả" }, "words.empty": { en: "No words yet", vi: "Chưa có từ nào" }, "words.emptyBody": { en: "Open a story, tap a word, and save it when you want it to return.", vi: "Mở một bài đọc, chạm vào một từ và lưu lại khi muốn nó quay lại." },
  "import.title": { en: "Make your own reading", vi: "Tạo bài đọc của riêng bạn" }, "import.intro": { en: "Paste Vietnamese text. Segmentation is a helpful approximation, not a linguistic authority.", vi: "Dán văn bản tiếng Việt. Tách từ chỉ là gợi ý gần đúng, không phải phán quyết ngôn ngữ." }, "import.titleLabel": { en: "Title", vi: "Tên bài" }, "import.textLabel": { en: "Vietnamese text", vi: "Văn bản tiếng Việt" }, "import.save": { en: "Save text", vi: "Lưu văn bản" }, "import.open": { en: "Open", vi: "Mở" }, "import.delete": { en: "Delete", vi: "Xóa" }, "import.saved": { en: "Saved locally to your account.", vi: "Đã lưu vào tài khoản của bạn." },
  "about.title": { en: "Read Vietnamese as it is", vi: "Đọc tiếng Việt như nó vốn có" }, "about.body": { en: "A small tool for beginners, with an ear pointed toward Đà Nẵng and Quảng Nam.", vi: "Một công cụ nhỏ cho người mới bắt đầu, với đôi tai hướng về Đà Nẵng và Quảng Nam." }, "about.noPressure": { en: "No pressure", vi: "Không áp lực" }, "about.noPressureBody": { en: "No streaks, hearts, XP, or daily guilt. The garden records what grew.", vi: "Không chuỗi ngày, tim, XP hay cảm giác tội lỗi. Khu vườn ghi lại điều đã lớn." }, "about.honest": { en: "Honest help", vi: "Trợ giúp trung thực" }, "about.honestBody": { en: "Difficulty and dialect notes are explained instead of pretending to be exact.", vi: "Độ khó và ghi chú phương ngữ được giải thích thay vì giả vờ chính xác." }, "about.open": { en: "Open material", vi: "Tư liệu mở" }, "about.openBody": { en: "Traditional texts are recorded with source and licence information.", vi: "Văn bản truyền thống được ghi rõ nguồn và giấy phép." },
  "error.INVALID_CREDENTIALS": { en: "The username or password is not correct.", vi: "Tên đăng nhập hoặc mật khẩu chưa đúng." }, "error.INVALID_USERNAME": { en: "Use 2–32 letters, numbers, dots, dashes, or underscores.", vi: "Dùng 2–32 chữ cái, số, dấu chấm, gạch ngang hoặc gạch dưới." }, "error.INVALID_PASSWORD": { en: "Use at least 6 characters.", vi: "Dùng ít nhất 6 ký tự." }, "error.SIGNUPS_CLOSED": { en: "Signups are closed.", vi: "Đăng ký đang đóng." }, "error.USERNAME_TAKEN": { en: "That username is already taken.", vi: "Tên đăng nhập này đã có người dùng." }, "error.UNKNOWN": { en: "Something went wrong. Try again.", vi: "Có lỗi xảy ra. Hãy thử lại." },
} as const satisfies Record<string, Bi>;
export type StringKey = keyof typeof STRINGS;
