import { Menu, X, Sun, Moon, Settings2, LogOut, Upload, Info, Sprout, Flower2, AudioLines, Languages, BookOpenText, RotateCcw } from "lucide-react";
import { useState, type ReactNode } from "react";
import type { AppView, StoryPattern, ThemeMode } from "../types";
import { T, useLang } from "../i18n"; import { useSpeech } from "../lib/speech";
import type { StringKey } from "../i18n/strings";
import type { User } from "../../shared/types";

export function PigMark({ small = false }: { small?: boolean }) { return <span className={"pig-mark" + (small ? " pig-mark--small" : "")} aria-hidden="true"><span className="pig-ear pig-ear--left" /><span className="pig-ear pig-ear--right" /><span className="pig-face"><span className="pig-eye pig-eye--left" /><span className="pig-eye pig-eye--right" /><span className="pig-snout"><i /><i /></span></span></span>; }
export function StoryMotif({ pattern }: { pattern: StoryPattern }) { return <div className={"story-motif story-motif--" + pattern} aria-hidden="true"><span className="motif-sun" /><span className="motif-hill motif-hill--back" /><span className="motif-hill motif-hill--front" /><span className="motif-animal"><span /></span><span className="motif-grass motif-grass--one" /><span className="motif-grass motif-grass--two" /></div>; }
const NAV = [{ view: "home", key: "nav.home", icon: Sprout }, { view: "library", key: "nav.library", icon: BookOpenText }, { view: "review", key: "nav.review", icon: RotateCcw }, { view: "tones", key: "nav.tones", icon: AudioLines }, { view: "words", key: "nav.words", icon: Languages }] as const satisfies ReadonlyArray<{ view: AppView; key: StringKey; icon: typeof Sprout }>;
export function AppHeader({ currentView, onNavigate, theme, onTheme, user, onSignOut }: { currentView: AppView; onNavigate: (view: AppView) => void; theme: ThemeMode; onTheme: () => void; user: User; onSignOut: () => Promise<void> }) { const [menuOpen, setMenuOpen] = useState(false); const { mode, setMode, t } = useLang(); const { voice, setVoice } = useSpeech(); return <header className="topbar"><button className="brand" onClick={() => onNavigate("home")} aria-label={t("app.tagline")}><PigMark small /><span className="brand-name"><T k="app.title" /></span><span className="brand-dialect"><T k="app.dialect" /></span></button><nav className="desktop-nav" aria-label={t("nav.home")}>{NAV.map(({ view, key }) => <button key={view} className={currentView === view ? "active" : ""} onClick={() => onNavigate(view)}><T k={key} /></button>)}</nav><div className="topbar-actions"><button className="icon-button" onClick={onTheme} aria-label={t("nav.theme")}>{theme === "light" ? <Sun size={18} /> : theme === "dark" ? <Moon size={18} /> : <Settings2 size={18} />}</button><button className="icon-button" onClick={() => void onSignOut()} aria-label={t("nav.signOut") + " " + user.username}><LogOut size={18} /></button><button className="icon-button menu-button" onClick={() => setMenuOpen((open) => !open)} aria-label={t("nav.menu")} aria-expanded={menuOpen}>{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></div>{menuOpen && <div className="overflow-menu"><label><Languages size={17} /><span>{t("nav.language")}</span><select value={mode} onChange={(event) => setMode(event.target.value as typeof mode)} aria-label={t("nav.language")}><option value="bilingual">{t("nav.languageBilingual")}</option><option value="english">{t("nav.languageEnglish")}</option><option value="vietnamese">{t("nav.languageVietnamese")}</option></select></label><label><AudioLines size={17} /><span>{t("nav.voice")}</span><select value={voice} onChange={(event) => setVoice(event.target.value as "myan" | "giahuy")} aria-label={t("nav.voice")}><option value="myan">My An</option><option value="giahuy">Gia Huy</option></select></label><button onClick={() => { onNavigate("garden"); setMenuOpen(false); }}><Flower2 size={17} /><T k="nav.garden" /></button><button onClick={() => { onNavigate("import"); setMenuOpen(false); }}><Upload size={17} /><T k="nav.import" /></button><button onClick={() => { onNavigate("about"); setMenuOpen(false); }}><Info size={17} /><T k="nav.about" /></button></div>}</header>; }
export function BottomNav({ currentView, onNavigate }: { currentView: AppView; onNavigate: (view: AppView) => void }) { return <nav className="bottom-nav" aria-label="Primary navigation">{NAV.map(({ view, key, icon: Icon }) => <button key={view} className={currentView === view ? "active" : ""} onClick={() => onNavigate(view)}><Icon size={20} strokeWidth={currentView === view ? 2.3 : 1.8} /><span><T k={key} /></span></button>)}</nav>; }
export function Pill({ children, tone = "neutral" }: { children: ReactNode; tone?: "neutral" | "red" | "green" | "ochre" }) { return <span className={"pill pill--" + tone}>{children}</span>; }
export function Toast({ message }: { message: string }) { return <div className="toast" role="status">{message}</div>; }
