import type { Bi, Sentence, Story, ToneKey } from "./types";
const bi = (en: string, vi: string): Bi => ({ en, vi });
const line = (id: string, translation: Bi, words: Array<string | [string, string]>): Sentence => ({ id, translation, tokens: words.map((word) => Array.isArray(word) ? { text: word[0], entry: word[1] } : { text: word }) });
export const STORIES: Story[] = [
  { id: "tier0-alphabet", title: "Chữ đặc biệt", titleEn: "Special letters", tier: 0, kind: "alphabet", region: "national", description: bi("Meet the letters English does not have.", "Làm quen với những chữ tiếng Anh không có."), source: "Original learning material", license: "original", pattern: "letter", interactive: "alphabet", sentences: [line("alphabet-1", bi("Vietnamese has a few letters worth meeting slowly.", "Tiếng Việt có vài chữ đáng làm quen thật chậm."), ["đ", "ă", "â", "ê", "ô", "ơ", "ư"])] },
  { id: "tier0-tones", title: "Năm đường nét", titleEn: "Five tone shapes", tier: 0, kind: "tonePrimer", region: "daNang", description: bi("See five written marks and hear a Central contour.", "Thấy năm dấu thanh và nghe một đường nét miền Trung."), source: "Original learning material", license: "original", pattern: "tone", interactive: "toneMatch", sentences: [line("tone-1", bi("A written mark points the reader; the voice brings it alive.", "Dấu viết chỉ đường; giọng nói làm nó sống."), ["thanh", "điệu"])] },
  { id: "tier0-first-words", title: "Những từ đầu tiên", titleEn: "First words", tier: 0, kind: "firstWords", region: "national", description: bi("A tiny first set: people, food, and going.", "Một nhóm nhỏ đầu tiên: người, thức ăn và việc đi."), source: "Original learning material", license: "original", pattern: "sprout", sentences: [line("first-1", bi("Mother and father eat rice.", "Mẹ và ba ăn cơm."), [["Mẹ", "mẹ"], ["và", "và"], ["ba", "ba"], ["ăn", "ăn"], ["cơm", "cơm"]]), line("first-2", bi("We go to Đà Nẵng.", "Chúng ta đi Đà Nẵng."), [["đi", "đi"], ["Đà Nẵng", "Đà Nẵng"]])] },
  { id: "dong-dao-con-co-be-be", title: "Con cò bé bé", titleEn: "The little stork", tier: 1, kind: "dongDao", region: "national", description: bi("A short rhyme for repetition, classifiers, and small steps.", "Một bài đồng dao ngắn để nhận ra lặp lại, loại từ và những bước nhỏ."), source: "Anonymous Vietnamese folk rhyme", license: "publicDomain", pattern: "stork", sentences: [line("co-1", bi("The little stork.", "Con cò bé bé."), [["Con", "con"], ["cò", "cò"], ["bé", "bé"], ["bé", "bé"]]), line("co-2", bi("It goes to the bamboo branch.", "Nó đi đến cành tre."), [["đi", "đi"], ["cành tre", "tre"]]), line("co-3", bi("It asks its mother.", "Nó hỏi mẹ."), [["hỏi", "hỏi"], ["mẹ", "mẹ"]])] },
  { id: "dong-dao-con-meo", title: "Con mèo trèo cây cau", titleEn: "The cat climbs the areca palm", tier: 1, kind: "dongDao", region: "national", description: bi("A children's verse with compound nouns and a clear rhythm.", "Một bài quen thuộc với cụm danh từ và nhịp rõ ràng."), source: "Anonymous Vietnamese folk rhyme", license: "publicDomain", pattern: "cat", sentences: [line("meo-1", bi("The cat climbs the areca palm.", "Con mèo trèo cây cau."), [["Con", "con"], ["mèo", "mèo"], ["cây cau", "cau"]]), line("meo-2", bi("The mouse asks where you are going.", "Chuột hỏi bạn đi đâu."), [["chuột", "chuột"], ["hỏi", "hỏi"], ["đi đâu", "đi"]])] },
  { id: "dong-dao-dung-dang", title: "Dung dăng dung dẻ", titleEn: "Walking hand in hand", tier: 1, kind: "dongDao", region: "national", description: bi("A movement rhyme: hold hands, walk out, and play.", "Một bài về chuyển động: nắm tay, đi ra và chơi."), source: "Anonymous Vietnamese folk rhyme", license: "publicDomain", pattern: "steps", sentences: [line("dung-1", bi("Walking hand in hand.", "Dung dăng dung dẻ."), [["dung", "dung"], ["dăng", "dung"], ["dung", "dung"], ["dẻ", "dung"]]), line("dung-2", bi("Lead the children out to play.", "Dắt trẻ đi chơi."), [["dắt", "dắt"], ["trẻ", "trẻ"], ["đi chơi", "chơi"]])] },
  { id: "ca-dao-dat-quang", title: "Đất Quảng Nam chưa mưa đã thấm", titleEn: "Quảng Nam earth soaks before rain", tier: 2, kind: "caDao", region: "quangNam", description: bi("A canonical Quảng Nam line: a place-name, climate, and local image.", "Một câu ca dao Quảng Nam: tên đất, khí hậu và hình ảnh địa phương."), source: "Anonymous Quảng Nam folk verse", license: "publicDomain", accent: "Quảng Nam", pattern: "dragon", sentences: [line("quang-1", bi("Quảng Nam earth is soaked before the rain.", "Đất Quảng Nam chưa mưa đã thấm."), [["đất", "đất"], ["Quảng Nam", "quảng"], ["chưa", "chưa"], ["mưa", "mưa"], ["đã", "đã"], ["thấm", "thấm"]]), line("quang-2", bi("The place holds water and memory.", "Vùng đất giữ nước và ký ức."), [["đất", "đất"], ["giữ", "giữ"], ["nước", "nước"], ["và", "và"]])] },
  { id: "dong-dao-keo-cua", title: "Kéo cưa lừa xẻ", titleEn: "Pull the saw, split the wood", tier: 2, kind: "dongDao", region: "central", description: bi("A work rhythm with repeated verbs and a meal at the end.", "Một nhịp lao động với động từ lặp lại và bữa cơm ở cuối."), source: "Anonymous Vietnamese folk rhyme", license: "publicDomain", pattern: "saw", sentences: [line("cua-1", bi("Pull the saw, split the wood.", "Kéo cưa, lừa xẻ."), [["kéo", "kéo"], ["cưa", "cưa"], ["gỗ", "gỗ"]]), line("cua-2", bi("The strong worker eats the king's meal.", "Người khỏe ăn cơm vua."), [["ăn", "ăn"], ["cơm", "cơm"], ["vua", "vua"]])] },
];
export const TONES: Array<{ key: ToneKey; label: Bi; mark: string; example: string; description: Bi; contour: number[] }> = [
  { key: "ngang", label: bi("level", "ngang"), mark: "", example: "ma", description: bi("steady and level", "cao và bằng"), contour: [0.5, 0.5, 0.5, 0.5, 0.5] },
  { key: "huyen", label: bi("falling", "huyền"), mark: "", example: "mà", description: bi("low and falling", "thấp dần"), contour: [0.6, 0.52, 0.44, 0.36, 0.3] },
  { key: "sac", label: bi("rising", "sắc"), mark: "´", example: "má", description: bi("bright and rising", "sáng và lên"), contour: [0.35, 0.44, 0.55, 0.7, 0.85] },
  { key: "hoi-nga", label: bi("dip / rise", "hỏi / ngã"), mark: "ˇ", example: "mả / mã", description: bi("down, then up", "hạ rồi lên"), contour: [0.58, 0.43, 0.28, 0.4, 0.62] },
  { key: "nang", label: bi("heavy", "nặng"), mark: ".", example: "mạ", description: bi("short and low", "ngắn và thấp"), contour: [0.45, 0.36, 0.25, 0.2, 0.18] },
];
export function allStorySentences(stories: Story[] = STORIES) { return stories.flatMap((story) => story.sentences.map((sentence) => ({ story, sentence }))); }
