import type { Bi, Sentence, Story, ToneKey } from "./types";
const bi = (en: string, vi: string): Bi => ({ en, vi });
const line = (id: string, translation: Bi, words: Array<string | [string, string]>): Sentence => ({ id, translation, tokens: words.map((word) => Array.isArray(word) ? { text: word[0], entry: word[1] } : { text: word }) });
export const STORIES: Story[] = [
  { id: "tier0-alphabet", title: "Chữ đặc biệt", titleEn: "Special letters", tier: 0, kind: "alphabet", region: "national", description: bi("Meet the letters English does not have.", "Làm quen với những chữ tiếng Anh không có."), source: "Original learning material", license: "original", pattern: "letter", interactive: "alphabet", sentences: [line("alphabet-1", bi("Vietnamese has a few letters worth meeting slowly.", "Tiếng Việt có vài chữ đáng làm quen thật chậm."), ["đ", "ă", "â", "ê", "ô", "ơ", "ư"])] },
  { id: "tier0-tones", title: "Năm đường nét", titleEn: "Five tone shapes", tier: 0, kind: "tonePrimer", region: "daNang", description: bi("See five written marks and hear a Central contour.", "Thấy năm dấu thanh và nghe một đường nét miền Trung."), source: "Original learning material", license: "original", pattern: "tone", interactive: "toneMatch", sentences: [line("tone-1", bi("A written mark points the reader; the voice brings it alive.", "Dấu viết chỉ đường; giọng nói làm nó sống."), ["thanh", "điệu"])] },
  { id: "tier0-first-words", title: "Những từ đầu tiên", titleEn: "First words", tier: 0, kind: "firstWords", region: "national", description: bi("A tiny first set: people, food, and going.", "Một nhóm nhỏ đầu tiên: người, thức ăn và việc đi."), source: "Original learning material", license: "original", pattern: "sprout", sentences: [line("first-1", bi("Mother and father eat rice.", "Mẹ và ba ăn cơm."), [["Mẹ", "mẹ"], ["và", "và"], ["ba", "ba"], ["ăn", "ăn"], ["cơm", "cơm"]]), line("first-2", bi("We go to Đà Nẵng.", "Chúng ta đi Đà Nẵng."), [["Chúng ta", "chúng ta"], ["đi", "đi"], ["Đà Nẵng", "Đà Nẵng"]])] },
  { id: "dong-dao-con-co-be-be", title: "Mẹ yêu không nào", titleEn: "Does Mother Love Me?", tier: 1, kind: "dongDao", region: "national", description: bi("The opening stanza of a well-known children's song, attributed rather than presented as folklore.", "Khổ mở đầu của một bài hát thiếu nhi quen thuộc, được ghi rõ tác giả thay vì xem là dân gian."), source: "Mẹ yêu không nào — Lê Xuân Thọ (opening excerpt)", sourceUrl: "https://truongca.com/images/sheet/pdf/me/me-yeu-khong-nao-le-xuan-tho-truongca.com.pdf", license: "copyrightedExcerpt", pattern: "stork", sentences: [line("co-1", bi("The little stork.", "Con cò bé bé."), [["Con", "con"], ["cò", "cò"], ["bé", "bé"], ["bé", "bé"]]), line("co-2", bi("It perches on a bamboo branch.", "Nó đậu cành tre."), [["Nó", "nó"], ["đậu", "đậu"], ["cành tre", "tre"]]), line("co-3", bi("It leaves without asking its mother.", "Đi không hỏi mẹ."), [["Đi", "đi"], ["không", "không"], ["hỏi", "hỏi"], ["mẹ", "mẹ"]]), line("co-4", bi("How would it know the way?", "Biết đi đường nào."), [["Biết", "biết"], ["đi", "đi"], ["đường nào", "đâu"]])] },
  { id: "dong-dao-con-meo", title: "Con mèo mà trèo cây cau", titleEn: "The cat climbs the areca palm", tier: 1, kind: "dongDao", region: "national", description: bi("A complete four-line folk verse with compound nouns and a clear rhythm.", "Một bài ca dao bốn dòng đầy đủ với cụm danh từ và nhịp rõ ràng."), source: "Anonymous Vietnamese folk verse", sourceUrl: "https://cadao.me/con-meo-ma-treo-cay-cau/", license: "publicDomain", pattern: "cat", sentences: [line("meo-1", bi("The cat climbs the areca palm.", "Con mèo mà trèo cây cau."), [["Con", "con"], ["mèo", "mèo"], ["mà", "mà"], ["trèo", "trèo"], ["cây cau", "cau"]]), line("meo-2", bi("It asks after the mouse, who is away.", "Hỏi thăm chú chuột đi đâu vắng nhà."), [["Hỏi thăm", "hỏi"], ["chú chuột", "chuột"], ["đi đâu", "đi"], ["vắng nhà", "nhà"]]), line("meo-3", bi("The mouse has gone to a faraway market.", "Chú chuột đi chợ đường xa."), [["Chú chuột", "chuột"], ["đi chợ", "chợ"], ["đường xa", "xa"]]), line("meo-4", bi("To buy fish sauce and salt for the cat's father's memorial meal.", "Mua mắm mua muối giỗ cha chú mèo."), [["Mua", "mua"], ["mắm", "mắm"], ["mua", "mua"], ["muối", "muối"], ["giỗ", "giỗ"], ["cha", "cha"], ["chú mèo", "mèo"]])] },
  { id: "dong-dao-dung-dang", title: "Dung dăng dung dẻ", titleEn: "Walking hand in hand", tier: 1, kind: "dongDao", region: "national", description: bi("The complete common nine-line version of a movement rhyme.", "Dị bản chín dòng phổ biến và đầy đủ của một bài đồng dao vận động."), source: "Anonymous Vietnamese folk game rhyme — Vietnam National Authority of Tourism", sourceUrl: "https://www.dulichvn.org.vn/index.php/item/25680", license: "publicDomain", pattern: "steps", sentences: [line("dung-1", bi("Walking hand in hand.", "Dung dăng dung dẻ."), [["Dung", "dung"], ["dăng", "dung"], ["dung", "dung"], ["dẻ", "dung"]]), line("dung-2", bi("Lead the children out to play.", "Dắt trẻ đi chơi."), [["Dắt", "dắt"], ["trẻ", "trẻ"], ["đi chơi", "chơi"]]), line("dung-3", bi("Arrive at heaven's gate.", "Đến cửa nhà trời."), [["Đến", "đến"], ["cửa", "cửa"], ["nhà trời", "trời"]]), line("dung-4", bi("Bow to the uncle and aunt.", "Lạy cậu lạy mợ."), [["Lạy", "lạy"], ["cậu", "cậu"], ["lạy", "lạy"], ["mợ", "mợ"]]), line("dung-5", bi("Let the child return home.", "Cho cháu về quê."), [["Cho", "cho"], ["cháu", "cháu"], ["về quê", "quê"]]), line("dung-6", bi("Send the goat to school.", "Cho dê đi học."), [["Cho", "cho"], ["dê", "dê"], ["đi học", "học"]]), line("dung-7", bi("Let the toad stay home.", "Cho cóc ở nhà."), [["Cho", "cho"], ["cóc", "cóc"], ["ở nhà", "nhà"]]), line("dung-8", bi("Let the chicken scratch by the stove.", "Cho gà bới bếp."), [["Cho", "cho"], ["gà", "gà"], ["bới", "bới"], ["bếp", "bếp"]]), line("dung-9", bi("Sit right down here.", "Ngồi xệp xuống đây."), [["Ngồi", "ngồi"], ["xệp", "xệp"], ["xuống đây", "đây"]])] },
  { id: "ca-dao-dat-quang", title: "Đất Quảng Nam chưa mưa đà thấm", titleEn: "Quảng Nam earth soaks before rain", tier: 2, kind: "caDao", region: "quangNam", description: bi("The canonical two-line Quảng Nam couplet, preserving the regional word đà.", "Cặp lục bát xứ Quảng quen thuộc, giữ nguyên từ địa phương đà."), source: "Anonymous Quảng Nam folk verse — Hội An Center for Cultural Heritage Management and Preservation", sourceUrl: "https://hoianheritage.danang.gov.vn/vi/trao-doi-chuyen-nganh/chuyen-de-nghien-cuu-trao-doi/do-thi-co-hoi-an-gia-tri-van-hoa-va-nghe-thuat-526.html", license: "publicDomain", accent: "Quảng Nam", pattern: "dragon", sentences: [line("quang-1", bi("Quảng Nam earth is soaked before the rain.", "Đất Quảng Nam chưa mưa đà thấm."), [["Đất", "đất"], ["Quảng Nam", "quảng"], ["chưa", "chưa"], ["mưa", "mưa"], ["đà", "đà"], ["thấm", "thấm"]]), line("quang-2", bi("Hồng Đào wine intoxicates before it is tasted.", "Rượu Hồng Đào chưa nhấm đà say."), [["Rượu", "rượu"], ["Hồng Đào", "hồng đào"], ["chưa", "chưa"], ["nhấm", "nhấm"], ["đà", "đà"], ["say", "say"]])] },
  { id: "dong-dao-keo-cua", title: "Kéo cưa lừa xẻ", titleEn: "Pull the saw back and forth", tier: 2, kind: "dongDao", region: "national", description: bi("The complete five-line common version of a saw-pulling game rhyme.", "Dị bản năm dòng phổ biến và đầy đủ của trò chơi kéo cưa."), source: "Anonymous Vietnamese folk game rhyme — Báo Pháp Luật Việt Nam", sourceUrl: "https://baophapluat.vn/keo-cua-lua-xe-post117403.html", license: "publicDomain", pattern: "saw", sentences: [line("cua-1", bi("Pull the saw back and forth.", "Kéo cưa lừa xẻ."), [["Kéo", "kéo"], ["cưa", "cưa"], ["lừa", "lừa"], ["xẻ", "xẻ"]]), line("cua-2", bi("Whichever worker is strong.", "Ông thợ nào khỏe."), [["Ông thợ", "thợ"], ["nào", "nào"], ["khỏe", "khỏe"]]), line("cua-3", bi("Returns to eat the king's rice.", "Về ăn cơm vua."), [["Về", "về"], ["ăn", "ăn"], ["cơm", "cơm"], ["vua", "vua"]]), line("cua-4", bi("Whichever worker loses.", "Ông thợ nào thua."), [["Ông thợ", "thợ"], ["nào", "nào"], ["thua", "thua"]]), line("cua-5", bi("Returns to nurse from mother.", "Về bú tí mẹ."), [["Về", "về"], ["bú", "bú"], ["tí", "tí"], ["mẹ", "mẹ"]])] },
];
export const TONES: Array<{ key: ToneKey; label: Bi; mark: string; example: string; description: Bi; contour: number[] }> = [
  { key: "ngang", label: bi("level", "ngang"), mark: "", example: "ma", description: bi("steady and level", "cao và bằng"), contour: [0.5, 0.5, 0.5, 0.5, 0.5] },
  { key: "huyen", label: bi("falling", "huyền"), mark: "", example: "mà", description: bi("low and falling", "thấp dần"), contour: [0.6, 0.52, 0.44, 0.36, 0.3] },
  { key: "sac", label: bi("rising", "sắc"), mark: "´", example: "má", description: bi("bright and rising", "sáng và lên"), contour: [0.35, 0.44, 0.55, 0.7, 0.85] },
  { key: "hoi-nga", label: bi("dip / rise", "hỏi / ngã"), mark: "ˇ", example: "mả / mã", description: bi("down, then up", "hạ rồi lên"), contour: [0.58, 0.43, 0.28, 0.4, 0.62] },
  { key: "nang", label: bi("heavy", "nặng"), mark: ".", example: "mạ", description: bi("short and low", "ngắn và thấp"), contour: [0.45, 0.36, 0.25, 0.2, 0.18] },
];
export function allStorySentences(stories: Story[] = STORIES) { return stories.flatMap((story) => story.sentences.map((sentence) => ({ story, sentence }))); }
