import { LogIn } from "lucide-react";
import { useState, type FormEvent } from "react";
import { api, ApiError } from "./lib/api";
import { ERROR_LABELS } from "./i18n/content";
import { T, useLang } from "./i18n";
import type { User } from "../shared/types";
export default function LoginView({ allowSignups, onSignedIn }: { allowSignups: boolean; onSignedIn: (user: User) => void }) {
  const [mode, setMode] = useState<"login" | "signup">("login"); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const { t } = useLang();
  const submit = async (event: FormEvent) => { event.preventDefault(); if (busy) return; setBusy(true); setError(""); try { const result = mode === "login" ? await api.login(username, password) : await api.signup(username, password); onSignedIn(result.user); } catch (caught) { const code = caught instanceof ApiError ? caught.code : "UNKNOWN"; setError(t(ERROR_LABELS[code as keyof typeof ERROR_LABELS] ?? ERROR_LABELS.UNKNOWN)); setBusy(false); } };
  return <main className="page login-page"><section className="login-card paper-card"><p className="eyebrow"><T k="app.title" /></p><h1>{mode === "login" ? "Welcome back" : "Create account"}</h1><p className="login-intro">A calm place to read Vietnamese, hear Central tones, and return to words when they are ready.</p><form onSubmit={submit}><label>Username<input value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" autoCapitalize="none" autoCorrect="off" spellCheck={false} required /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete={mode === "login" ? "current-password" : "new-password"} required /></label>{error && <p className="login-error" role="alert">{error}</p>}<button className="primary-button" type="submit" disabled={busy}><LogIn size={17} /> {busy ? "Signing in…" : mode === "login" ? "Sign in" : "Create account"}</button></form>{allowSignups && <button className="link-button" type="button" onClick={() => { setMode(mode === "login" ? "signup" : "login"); setError(""); }}>{mode === "login" ? "Need an account? Create one." : "Already have an account? Sign in."}</button>}</section></main>;
}
