import { useMemo, useState } from "react";
import { Check, CloudDownload, Info, Upload } from "lucide-react";
import type { ImportRecord } from "../lib/api";
import type { Story } from "../types";
import { T } from "../i18n"; import { useSpeech } from "../lib/speech";
import { api } from "../lib/api";
import { segmentImport, storyFromImport } from "../lib/imports";
import { estimateStory } from "../lib/difficulty";
import { Pill, PigMark } from "../components/ui";
export default function ImportView({ imports, onSaved, onOpen }: { imports: ImportRecord[]; onSaved: () => Promise<void>; onOpen: (story: Story) => void }) {
  const { speak } = useSpeech(); const [title, setTitle] = useState(""); const [raw, setRaw] = useState(""); const [saved, setSaved] = useState(false); const tokens = useMemo(() => segmentImport(raw), [raw]);
  const estimate = useMemo(() => estimateStory(storyFromImport({ id: 0, title: title || "Your text", raw, importedAt: 0, difficulty: 0 }), {}, false), [title, raw]);
  const save = async () => { if (!raw.trim()) return; await api.addImport(title.trim() || "My Vietnamese text", raw.trim(), estimate.score); setSaved(true); await onSaved(); };
  return <main className="page feature-page import-page"><section className="feature-heading"><div><p className="eyebrow"><T k="nav.import" /></p><h1><T k="import.title" /></h1><p><T k="import.intro" /></p></div><div className="local-only"><CloudDownload size={20} /><span>Account data</span></div></section><section className="import-workspace"><div className="import-form paper-card"><label><T k="import.titleLabel" /><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="A morning by the sea" /></label><label><T k="import.textLabel" /><textarea value={raw} onChange={(event) => { setRaw(event.target.value); setSaved(false); }} placeholder="Paste Vietnamese text here…" rows={10} /></label><div className="import-form-bottom"><span>{tokens.length} tokens · {estimate.band}</span><button className="primary-button" onClick={() => void save()} disabled={!raw.trim()}><Upload size={17} /> <T k="import.save" /></button></div>{saved && <p className="save-confirm"><Check size={16} /> <T k="import.saved" /></p>}</div><div className="import-preview paper-card"><div className="preview-title"><h2>{title || "Your reading"}</h2><Pill tone="ochre">{estimate.band}</Pill></div>{raw ? <div className="preview-tokens">{tokens.map((token, index) => <button key={token + index} title="Listen" onClick={() => speak(token)}>{token}</button>)}</div> : <div className="preview-empty"><PigMark /><p>Preview appears here.</p></div>}<p className="approx-note"><Info size={15} /> Segmentation is approximate.</p><p className="approx-note"><Info size={15} /> Playback sends the selected text to FPT.AI for audio generation.</p></div></section>{imports.length > 0 && <section className="saved-imports"><h2><T k="import.saved" /></h2>{imports.map((item) => <article key={item.id} className="paper-card"><div><strong>{item.title}</strong><p>{item.raw.slice(0, 100)}{item.raw.length > 100 ? "…" : ""}</p></div><div className="saved-actions"><Pill>{item.difficulty}/10</Pill><button className="text-button" onClick={() => onOpen(storyFromImport(item))}><T k="import.open" /></button><button className="text-button" onClick={() => void api.deleteImport(item.id).then(onSaved)}><T k="import.delete" /></button></div></article>)}</section>}</main>;
}
