import { useEffect, useState } from "react";
import { Play, Volume2, X } from "lucide-react";
import { Rating } from "ts-fsrs";
import type { CardRecord, QueueResponse } from "../lib/api";
import { api } from "../lib/api";
import { STORIES } from "../data";
import { T, useLang } from "../i18n";
import { speakVietnamese } from "../lib/speech";
import { PigMark } from "../components/ui";
function sourceSentence(card: CardRecord): string { for (const story of STORIES) for (const sentence of story.sentences) if (sentence.id === card.sourceSentenceId) return sentence.tokens.map((token) => token.text).join(" "); return ""; }
export default function ReviewView() {
  const [minutes, setMinutes] = useState(5); const [queue, setQueue] = useState<QueueResponse | null>(null); const [started, setStarted] = useState(false); const [index, setIndex] = useState(0); const [revealed, setRevealed] = useState(false); const [startedAt, setStartedAt] = useState(0); const [remaining, setRemaining] = useState(0); const { t } = useLang();
  useEffect(() => { void api.queue(20).then(setQueue).catch(() => setQueue({ cards: [], budgetMs: 0, serverNow: Date.now(), forgiveness: null, newCount: 0 })); }, []);
  useEffect(() => { if (!started) return; const timer = window.setInterval(() => { const left = Math.max(0, minutes * 60000 - (Date.now() - startedAt)); setRemaining(left); if (left <= 0) { setStarted(false); setIndex(0); setRevealed(false); } }, 250); return () => window.clearInterval(timer); }, [minutes, started, startedAt]);
  const current = queue?.cards[index]; const leftMinutes = Math.ceil(remaining / 60000);
  const rate = async (rating: Rating) => { if (!current) return; const response = await api.reviewCard(current.id, rating); const next = [...(queue?.cards ?? [])]; if (response.card.due <= Date.now() + minutes * 60000 && !next.some((card, cardIndex) => card.id === response.card.id && cardIndex > index)) next.push(response.card); setQueue((value) => value ? { ...value, cards: next } : value); setRevealed(false); if (index + 1 < next.length) setIndex(index + 1); else setStarted(false); };
  if (!started) return <main className="page feature-page review-page"><section className="feature-heading"><div><p className="eyebrow"><T k="nav.review" /></p><h1><T k="review.title" /></h1><p><T k="review.intro" /></p></div><div className="review-clock"><span>{minutes}</span><small><T k="review.minutes" /></small></div></section><section className="session-picker paper-card"><div>{[5, 10, 20].map((value) => <button key={value} className={minutes === value ? "active" : ""} onClick={() => setMinutes(value)}>{value} <T k="review.minutes" /></button>)}</div>{queue?.forgiveness && <p className="save-confirm"><T k="review.forgiveness" /></p>}{queue && queue.cards.length > 0 ? <button className="primary-button" onClick={() => { setStartedAt(Date.now()); setRemaining(minutes * 60000); setIndex(0); setRevealed(false); setStarted(true); }}><Play size={17} /> <T k="review.start" /></button> : <div className="empty-review"><PigMark /><h2><T k="review.emptyTitle" /></h2><p><T k="review.emptyBody" /></p></div>}</section></main>;
  if (!current) return null;
  const context = sourceSentence(current); const leftText = leftMinutes <= 1 ? t("review.almost") : t("review.left").replace("{minutes}", String(leftMinutes));
  return <main className="page review-session"><div className="review-session-top"><button className="back-button" onClick={() => setStarted(false)}><X size={18} /> <T k="review.end" /></button><span>{leftText}</span></div><div className="review-progress"><i style={{ width: Math.min(100, ((minutes * 60000 - remaining) / Math.max(minutes * 60000, 1)) * 100) + "%" }} /></div><section className="flash-card paper-card"><p className="eyebrow"><T k="review.context" /></p><button className="word-audio" onClick={() => speakVietnamese(current.entry)} aria-label="Listen"><Volume2 size={18} /></button><h1 lang="vi">{current.entry}</h1>{!revealed ? <button className="primary-button reveal-button" onClick={() => setRevealed(true)}><T k="review.reveal" /></button> : <><p className="flash-gloss">{current.gloss}</p>{context && <p className="context-line" lang="vi">{context}</p>}<div className="rating-row"><button onClick={() => void rate(Rating.Again)}><T k="review.again" /></button><button onClick={() => void rate(Rating.Hard)}><T k="review.hard" /></button><button onClick={() => void rate(Rating.Good)}><T k="review.good" /></button><button onClick={() => void rate(Rating.Easy)}><T k="review.easy" /></button></div></>}</section></main>;
}
